### PR TITLE
Set API version to 3.0.1

### PR DESCRIPTION
**Pull request by Cousjava**
Signed-off-by: Jonathan Coustick <jonathan.coustick@payara.fish>

### CODE REVIEW

**Comment by markt-asf** [comment]
This needs to be reverted. The last EL release from Oracle was 3.0.1-b06 so the first release from Eclipse needs to be 3.0.2.

**Comment by arjantijms** [comment]
@markt-asf 

Are you sure? If you look at the other -b releases, they seem to be releases before the actual release.

They seem to be a kind of beta releases. Seemingly there never was a 3.0.1 (final).

**Comment by arjantijms** [comment]
For example look at 3.0.0: https://mvnrepository.com/artifact/javax.el/javax.el-api
screenshot 2018-11-07 at 20 54 12

There are 8 b releases first, and then there's the 3.0.0 proper release.

**Comment by markt-asf** [comment]
I stand corrected. The gaps in my Maven knowledge are showing. I didn't realise that `b` was treated as a `BETA`.
I still like the idea of starting at 3.0.2 as it creates a clear separation from the Oracle releases. I'm not sure if the fact that 3.0.2 is already on staging is an issue. It can be removed. The problem will be if someone has already used it. Given version numbers are cheap, sticking with 3.0.2 might be the safest option.

**Pull request merged**
