### PR TITLE
ensure that we always exitLambdaScope()

### PR DESCRIPTION
**Pull request by scottmarlow**
Signed-off-by: Scott Marlow <smarlow@redhat.com>

Apply fix for  [JBEE-158](https://issues.jboss.org/browse/JBEE-158)

### CODE REVIEW

**Comment by arjantijms** [comment]
Looks good. I think it's fine, but will run the TCK against it first.

**Comment by scottmarlow** [comment]
With the change, the only impact should be when exceptions are thrown in that the finally clause will ensure that parameters are popped or not leaked by the ELContext.  

This was originally fixed [for JBEE-158 via pull request link](https://github.com/jboss/jboss-el-api_spec/commit/1de218cdbd1ece977dfc1a42d96bfffd127d44f1) and our testing has been passing since the change was made.  We try to fix issues like this upstream first but I'm not sure why that didn't happen, so here we are now, submitting the fix for upstream. :)

**Comment by scottmarlow** [comment]
@arjantijms the Jakarta EE 8 platform TCK has been passing for me when using the [jboss-jakarta-el-api_spec fork](https://github.com/jboss/jboss-jakarta-el-api_spec) which contains this change also.

**Comment by arjantijms** [comment]
@markt-asf Thanks for merging this. Because of my new customers and other work I have had extremely little time to look at this, so thanks for doing it!

**Pull request merged**
