### PR TITLE
Revert "Prepare for RC1 combined release"

### PR DESCRIPTION
**Pull request by arjantijms**
This reverts commit 0d19b582185d91d20138c9aa66f8b66e762a0c8b.

### CODE REVIEW

**Comment by pzygielo** [comment]
Can tag be moved back as well?

**Comment by arjantijms** [comment]
That's a good question. There's technically still an RC release done from that tag. What I think we need eventually is 3 tags, for the impl, the api and the combined, although we don't often release the impl only one (if at all). I just renamed the current tag to indicate it's for the combo release (as several of the other tags are as well)

**Comment by pzygielo** [comment]
1. I think that the **updated/moved** tag [4.0.0-RC1-RELEASE](https://github.com/eclipse-ee4j/el-ri/releases/tag/4.0.0-RC1-RELEASE) - now attached to ad05833, previously pointed to version used to release [jakarta.el:jakarta.el-api:4.0.0-RC1](https://repo1.maven.org/maven2/jakarta/el/jakarta.el-api/4.0.0-RC1). My best guess is it was 
```shell
$ git cat-file tag d5ba8a8864c27f47314a6323caaa6a623d4005ec
object 8a438c0aa8f5708899dd541b52c5746e413ecaf6
type commit
tag 4.0.0-RC1-RELEASE
tagger Eclipse EL-api Bot <el-bot@eclipse.org> 1580406061 +0000

Release jakarta.el:jakarta.el-api:4.0.0-RC1
```
(for commit 8a438c0aa8f5708899dd541b52c5746e413ecaf6 - which for example does not contain 62d688b). I'd like _that_ to be restored. 

2. On the other hand - the new [4.0.0-RC1-RELEASE-COMBO](https://github.com/eclipse-ee4j/el-ri/releases/tag/4.0.0-RC1-RELEASE-COMBO) points at version not used to release [org.glassfish:jakarta.el:4.0.0-RC1](https://repo1.maven.org/maven2/org/glassfish/jakarta.el/4.0.0-RC1/)

**Comment by arjantijms** [comment]
> On the other hand - the new 4.0.0-RC1-RELEASE-COMBO points at version not used to release org.glassfish:jakarta.el:4.0.0-RC1

I just noticed that too. Apparently GitHub moves a tag to the current head when you rename it.

**Comment by markt-asf** [comment]
I *really* don't like that we now have two different 4.0.0-RC1 release tags for the API. An RC1 implementation only release from the existing RC1 tag or an RC2 combo release would have been better.
I've restored the 4.0.0-RC1-RELEASE tag from my local checkout.
I'll see if I can figure out where the 4.0.0-RC1-RELEASE-COMBO tag should be placed.

**Comment by markt-asf** [comment]
Best I can tell  4.0.0-RC1-RELEASE-COMBO should point to
0d19b582185d91d20138c9aa66f8b66e762a0c8b
Any objections to me resetting that tag to point to that commit?

**Comment by arjantijms** [comment]
Hi Mark, no objections.

I too don't like the different tags and releases, I can hardly imagine anyone does. 

Unfortunately we were in the same situation before. The previous releases were done in pretty much the same way. Would be good if we structured this a little. Maybe we need to rethink if we need the combined release at all? For now this was needed since a ton of existing projects depend on that (among which Mojarra), but this can always be changed.

**Comment by markt-asf** [comment]
Lets have a discussion about that on the el-dev mailing list.

**Pull request merged**
