### PR TITLE
Prepare for RC1 combined release

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Comment by markt-asf** [comment]
Huh?

1. We have already had an RC1. Trying to create a duplicate is going to cause all sorts of breakage.
2. The exact version is set in the parameters used to call the CI scripts that create the release. They should not be set here.

Please revert.

**Comment by arjantijms** [comment]
Hi Mark, I think the RC1 that we had is the API only. At least in Maven Central and in staging I didn't see any combined release. 

That release is there now: https://repo1.maven.org/maven2/org/glassfish/jakarta.el/4.0.0-RC1/

As for setting the RC1 version in the repo vs setting it in the script parameters, I guess that's two different ways to do the same thing. If I'm not mistaken one of the mailing lists mentioned the repo way, and I've been using that. It was also said that project could (or was it should?) revert back to -SNAPSHOT after an RC, and then set RC2 when/if it's time to release that.

**Comment by arjantijms** [comment]
See https://github.com/eclipse-ee4j/el-ri/pull/121

**Comment by markt-asf** [comment]
My understanding is that releases should be done via the CI system. There should not be any need for version number manipulation outside of that. I'll follow up separately on #121

**Comment by arjantijms** [comment]
Hi,

On Sat, Mar 7, 2020 at 6:53 PM Mark Thomas <notifications@github.com> wrote:

> My understanding is that releases should be done via the CI system. There
> should not be any need for version number manipulation outside of that.
> I'll follow up separately on #121
> <https://github.com/eclipse-ee4j/el-ri/pull/121>
>

For the final release staging the CI scripts automatically remove the
-SNAPSHOT and increase the version number, but most (not all) also allow
you to set the release and next version manually. Until now I've not used
the manual way.

The -RCx releases are new though, and there's not much best practices yet
for this (or, I've missed it). I've seen a couple of projects indeed set
the -RCx version in the repo, and then do the release based on that. You
are right that we could say to only set the RCx versions manually in the CI
system. Probably this is a good discussion to have at the platform level.

Kind regards,
Arjan

**Pull request merged**
