### PR TITLE
change from javax.* to jakarta.*

### PR DESCRIPTION
**Pull request by scottmarlow**
Initial changes for javax.* to jakarta.* package rename. Where should we share changes like this? Perhaps via an EE9 or EE4J_9 branch?

FYI, planning for Jakarta EE 9 is not yet complete, but I think that some might want to start working on potential changes.  I'm sharing this, so such (pre planning) efforts could use it.

Signed-off-by: Scott Marlow <smarlow@redhat.com>

### CODE REVIEW

**Comment by arjantijms** [comment]
Hi Scott, there have been some different discussions about where things should go. At least for Jakarta EE 8 many specs (but not all) did their work in the master branch, as that is representing the main version going forward.

**Comment by markt-asf** [comment]
+1 to working in master. In the unlikely event we need to do something for Jakarta EE 8, we can branch from the tag and work form there.

**Comment by arjantijms** [comment]
> I'd also like to see the inserts of ELUtil. ... in a separate commit

If there's no explicit reason to insert those `ELUtil.` prefixes, we might as well leave them out. I guess some automatic tool might have added them?

**Comment by scottmarlow** [comment]
I used intellij to make the changes, not sure why trailing spaces were deleted yet, will figure that out or make the change again without intellij.  I'm also not sure about the ElUtil issue, easy to fix that manually.

**Comment by scottmarlow** [comment]
I added a TODO to api/src/main/java/jakarta/el/ExpressionFactory.java, as the javax.el in properties should probably change also.

Disabling the Intellij [EditorConfig plugin, helped avoid the removal of trailing spaces](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000038550-Intelij-removes-trailing-space-while-writing-comment).  I made the package changes again and pushed.

**Comment by markt-asf** [comment]
I agree the property name in ExpressionFactory needs to change as well.
I thought about keeping javax.el.ExpressionFactory as a fall-back but, because of the package change, the implementations won't be compatible so I don't think there is any point in doing so.
I've only looked at the API, not the impl.

**Comment by scottmarlow** [comment]
I pushed some property name changes, jakarta.el.bc2.2 replaced javax.el.bc2.2 and added javadoc for the ExpressionFactoryImpl#coerceToType that mentions the jakarta.el.bc2.2 property.

**Comment by scottmarlow** [comment]
Should we bump the spec version number to 4.0?  If not, I'll update the last commit and squash that part of the change.

**Pull request merged**
