### PR TITLE
[issue-78] EL expressions that contain unnecessary parentheses fail

### PR DESCRIPTION
**Pull request by tmiyargi**
Added change from https://svn.apache.org/viewvc?view=revision&revision=1571242
Regenerated the parser and added a test.

### CODE REVIEW

**Comment by tmiyargi** [comment]
All changes are now in place, headers included and I have signed the Contributor Agreement.

**Comment by bshannon** [comment]
@markt-asf It looks like you were the author of the [original fix to the Apache code](https://svn.apache.org/viewvc?view=revision&revision=1571242).
Why don't you just apply that fix, which you still own, to the EE4J code,
under the Eclipse license?

**Comment by tmiyargi** [comment]
@markt-asf @bshannon should I close this PR then so you can add the changes yourselves?

**Comment by bshannon** [comment]
@markt-asf, it's up to you.  Can you just apply your fix, under the Eclipse license?

**Comment by DennisBayer** [comment]
Hi there,

any updates on this issue @markt-asf ? Additionally, is there any timeline for a release which would contain this fix?

Best regards
Dennis

**Comment by tmiyargi** [comment]
I've reworked the fix so it is no longer a copy. I hope you can merge it now.

**Comment by bshannon** [comment]
It looks like @markt-asf has checked out of this project since he's not responding.
I've dismissed his review.  We should consider removing him as a Committer.

The latest changes contain a lot of gratuitous formatting changes, is that because
these files were regenerated?  Unfortunately, that makes it harder to review the
changes.

In any event, this needs review by someone more familiar with this code.  I've added
some other reviewers who might be able to help.

**Comment by tmiyargi** [comment]
@bshannon To files have been changed the others are regenerated using JavaCC. Thank you for looking into this.

**Comment by markt-asf** [comment]
My interest in EL at Eclipse is limited to the API.
Contributing to the implementation is not an itch I have any motivation to scratch.
The sole reason for my commenting on this PR was to point out that the original PR did not meet the requirements of the open source license of the project from which it was copied.

**Comment by bshannon** [comment]
> The sole reason for my commenting on this PR was to point out that the original PR did not meet the requirements of the open source license of the project from which it was copied.

Which you could've solved by contributing your fix to this project as well.
That would've been simple for you to do.  It's disappointing that you're
not willing to do so.

**Comment by tmiyargi** [comment]
Done rebase and solved conflicts, @arjantijms, @ruolli could you have a look?

**Comment by bmaxwell** [comment]
@arjantijms / @ruolli  any updates on if this change is acceptable?

**Comment by rmartinc** [comment]
Hi,

The only real changes in this PR are in the following files:

* impl/src/main/java/com/sun/el/parser/ELParser.jjt
* src/test/java/org/glassfish/el/test/ELProcessorTest.java
* src/test/java/org/glassfish/el/test/LambdaTest.java
* src/test/java/org/glassfish/el/test/OperatorTest.java

All the other changes are result of executing the `ant` with the file `impl/build.xml`, which in turns executes `JavaCC` and regenerates the Java files for the EL parser. Maybe you feel more comfortable if only the modified files are included in the PR, the review will be easier. Later you can re-execute the `ant` and re-generate the auto-generated files by your own. WDYT?

**Comment by rmartinc** [comment]
Hi,

Sorry again for asking about this, but can we do something to move the PR forward? I proposed to send just one commit but maybe it's better if two commits are sent in the PR (the real modifications and then another one with the automatic ones). @tmiyargi cannot work more on the issue, so we'll need to send another PR for this.

Thanks!

**Comment by rmartinc** [comment]
Thanks a lot @bshannon !!!

**Pull request merged**
